FROM python:3.9

WORKDIR /app/python_api

EXPOSE 4444

COPY ./python_api/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5175"]