version: "3"
services:
  chatgpt_web:
    container_name: chatgpt_web
    restart: always
    depends_on:
      - python_api
    env_file:
      - .env
    ports:
      - 5173:5173
    volumes:
      - .:/app
    build:
      context: "."
      dockerfile: Dockerfile
      
  python_api:
    container_name: python_api
    restart: always
    ports:
      - 5175:5175
      - 4444:4444  # Map the pdb port
    volumes:
      - ./python_api:/app/python_api
    build:
      context: "."
      dockerfile: python_api/Dockerfile-pythonapi
    environment:
      - OPENAI_API_KEY
      - DEBUG=1  # Enable debug mode